changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🛠 Breaking Changes
      labels:
        - breaking-change
    - title: 🏕 Features
      labels:
        - enhancement
    - title: Bug
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"

